"use client";

import React from "react";
import {
  Banknote, GraduationCap, Zap, Landmark, Bus, Hospital, BarChart, MessageCircle, 
  MapPin, Wheat, Calculator, Smartphone, Book, Baby, Target, FileText, 
  Calendar, Car, Phone, School, Home, Building2, Shield, AlertTriangle, 
  FileBadge, Contact, Mailbox, Droplets, Sun, CheckSquare, PawPrint, 
  BadgeCheck, Building, Luggage, CloudRain, Soup, Sprout, Mountain, 
  Tractor, FlaskConical, Store, TreePine, Globe, CalendarDays, Trophy,
  HelpCircle, Lightbulb, Lock, Search, Scale, Key, PenTool, Settings, 
  File, Mail, Megaphone, Flag, Check, CreditCard, Vote, TrendingUp, Link, 
  Map, BusFront, MapPinCheck, PhoneCall, PartyPopper, ShieldCheck, Leaf, 
  CloudSun, X, ClipboardList, CheckCircle2, Footprints, Ruler, TriangleAlert, 
  Handshake, Siren, CalendarRange, XCircle, User, Inbox, BuildingIcon, 
  AtSign, Globe2, BookOpen, Umbrella, ScrollText, Palette, Cookie, Gamepad2, 
  Type, Frown, Rocket, ThumbsUp, HelpCircleIcon, Dumbbell, BookOpenCheck, 
  HeartCrack, Crown, Sparkles, FlagTriangleRight, MapPinIcon, Amphora, 
  MessageSquare, Hand, Hash, Users, Pointer, Ban, FlipHorizontal, Puzzle, 
  RefreshCw, Users2, Activity, UtensilsCrossed, Wind, Badge, AlertCircle, 
  HomeIcon, Hammer, BaggageClaim, Medal, Flame, Brain, Cherry, Coffee, 
  ShoppingCart, Ship, TrendingDown, ArrowRightLeft, Beef, Milk, CarFront, 
  Beer, Wrench, TrafficCone
} from "lucide-react";

interface DynamicIconProps {
  emoji?: string;
  className?: string;
}

const iconMap: Record<string, React.ElementType> = {
  // Original
  "💰": Banknote,
  "🎓": GraduationCap,
  "⚡": Zap,
  "🏛️": Landmark,
  "🏛": Landmark,
  "🚌": BusFront,
  "🏥": Hospital,
  "📊": BarChart,
  "🗣️": MessageCircle,
  "🗣": MessageCircle,
  "📍": MapPin,
  "🌾": Wheat,
  "🧮": Calculator,
  "📱": Smartphone,
  "📚": Book,
  "👶": Baby,
  "🎯": Target,
  "📝": FileText,
  "📅": Calendar,
  "🚗": Car,
  "📞": Phone,
  "🏫": School,
  "🏠": Home,
  "🏗️": Building2,
  "🏗": Building2,
  "🛡️": ShieldCheck,
  "🛡": ShieldCheck,
  "🚦": TrafficCone,
  "🛂": FileBadge,
  "🪪": Contact,
  "📮": Mailbox,
  "💧": Droplets,
  "☀️": Sun,
  "☀": Sun,
  "🗳️": CheckSquare,
  "🗳": Vote,
  "🦁": PawPrint,
  "™️": BadgeCheck,
  "🏘️": Building,
  "🏘": Building,
  "🛃": Luggage,
  "🌧️": CloudRain,
  "🌧": CloudRain,
  "🍲": Soup,
  "🌱": Sprout,
  "🏔️": Mountain,
  "🏔": Mountain,
  "🐄": Tractor,
  "🧪": FlaskConical,
  "🏪": Store,
  "🌲": TreePine,
  "🌍": Globe,
  "📆": CalendarDays,
  "🏆": Trophy,
  
  // New Additions
  "💡": Lightbulb,
  "🔒": Lock,
  "🔍": Search,
  "⚖": Scale,
  "⚖️": Scale,
  "🔐": Key,
  "✏": PenTool,
  "✏️": PenTool,
  "✍": PenTool,
  "⚙": Settings,
  "⚙️": Settings,
  "📄": File,
  "✉": Mail,
  "✉️": Mail,
  "📢": Megaphone,
  "🚩": Flag,
  "✓": Check,
  "✅": CheckCircle2,
  "💳": CreditCard,
  "📈": TrendingUp,
  "🔗": Link,
  "🗺": Map,
  "🎉": PartyPopper,
  "🌦": CloudSun,
  "🌦️": CloudSun,
  "❌": X,
  "✗": XCircle,
  "📋": ClipboardList,
  "🥾": Footprints,
  "📐": Ruler,
  "⚠": TriangleAlert,
  "⚠️": TriangleAlert,
  "🤝": Handshake,
  "🚨": Siren,
  "🗓": CalendarRange,
  "👤": User,
  "📥": Inbox,
  "🏢": BuildingIcon,
  "📧": AtSign,
  "🌐": Globe2,
  "🏖": Umbrella,
  "📜": ScrollText,
  "🎨": Palette,
  "🍪": Cookie,
  "🎮": Gamepad2,
  "🔤": Type,
  "😔": Frown,
  "🚀": Rocket,
  "👍": ThumbsUp,
  "🤷": HelpCircleIcon,
  "💪": Dumbbell,
  "📖": BookOpenCheck,
  "💔": HeartCrack,
  "👑": Crown,
  "✨": Sparkles,
  "🏁": FlagTriangleRight,
  "🚏": MapPinIcon,
  "🏺": Amphora,
  "💬": MessageSquare,
  "👋": Hand,
  "🔢": Hash,
  "❓": HelpCircle,
  "👥": Users,
  "👉": Pointer,
  "🚫": Ban,
  "🪞": FlipHorizontal,
  "🧩": Puzzle,
  "🔄": RefreshCw,
  "👨": User,
  "👩": User,
  "👧": User,
  "👦": User,
  "👨‍👩‍👧‍👦": Users2,
  "🫁": Activity,
  "🌿": Leaf,
  "💨": Wind,
  "📛": Badge,
  "😮": AlertCircle,
  "⚒": Hammer,
  "⚒️": Hammer,
  "🧳": BaggageClaim,
  "🏡": HomeIcon,
  "🥉": Medal,
  "🥈": Medal,
  "🥇": Trophy,
  "💎": Trophy,
  "🔥": Flame,
  "🏅": Medal,
  "🧠": Brain,
  "🌽": Wheat,
  "🫘": Wheat,
  "🥔": Wheat,
  "🍵": Coffee,
  "☕": Coffee,
  "🍅": Cherry,
  "🥬": Leaf,
  "🎋": TreePine,
  "🥑": Cherry,
  "🍌": Cherry,
  "🛒": ShoppingCart,
  "🏦": Landmark,
  "🚢": Ship,
  "📉": TrendingDown,
  "💱": ArrowRightLeft,
  "🥩": Beef,
  "🥛": Milk,
  "🍡": Coffee,
  "🐐": Tractor,
  "🐑": Tractor,
  "🐪": Tractor,
  "🏎": CarFront,
  "🍺": Beer,
  "🔧": Wrench,
  "🚶": Footprints
};

export default function DynamicIcon({ emoji, className = "w-5 h-5" }: DynamicIconProps) {
  if (!emoji) return null;

  // Handle composite emojis like families or flags
  if (emoji === "🇰🇪") {
    return <MapPin className={className} />;
  }
  if (emoji === "👨‍👩‍👧‍👦") {
    return <Users2 className={className} />;
  }

  // If the emoji has invisible variation selectors, trim them or normalize
  const cleanEmoji = emoji.replace(/[\uFE0F]/g, '');
  
  // Try to find an exact match first, then a cleaned match
  const IconComponent = iconMap[emoji] || iconMap[cleanEmoji] || HelpCircle;
  
  return <IconComponent className={className} />;
}
