import { ToolCategory, Tool } from './types';

export const TOOL_CATEGORIES: { id: ToolCategory; name: string; icon: string; description: string; badgeClass: string }[] = [
  { id: 'finance-tax', name: 'Finance & Tax', icon: '💰', description: 'Salary calculators, tax tools, and financial guides', badgeClass: 'badge-finance' },
  { id: 'education-cbc', name: 'Education & CBC', icon: '🎓', description: 'CBC curriculum, KUCCPS clusters, exam calculators', badgeClass: 'badge-education' },
  { id: 'utilities-energy', name: 'Utilities & Energy', icon: '⚡', description: 'Power outages, token calculators, fuel prices', badgeClass: 'badge-utilities' },
  { id: 'government-legal', name: 'Government & Legal', icon: '🏛️', description: 'Tenders, public holidays, government services', badgeClass: 'badge-government' },
  { id: 'transport-travel', name: 'Transport & Travel', icon: '🚌', description: 'Number plates, matatu routes, distances', badgeClass: 'badge-transport' },
  { id: 'health-wellness', name: 'Health & Wellness', icon: '🏥', description: 'NHIF hospitals, vaccination schedules', badgeClass: 'badge-health' },
  { id: 'business-investment', name: 'Business & Investment', icon: '📊', description: 'Registration costs, SACCO directory', badgeClass: 'badge-business' },
  { id: 'data-reference', name: 'Data & Reference', icon: '📍', description: 'Postal codes, phone prefixes, demographics', badgeClass: 'badge-reference' },
  { id: 'agriculture-environment', name: 'Agriculture & Environment', icon: '🌾', description: 'Crop calendars, soil types, livestock prices', badgeClass: 'badge-agriculture' },
];

export const TOOLS: Tool[] = [
  {
    slug: 'paye-calculator',
    title: 'Kenya PAYE Salary Calculator 2025/2026',
    shortTitle: 'PAYE Calculator',
    description: 'Calculate your net salary after PAYE tax, NHIF, NSSF, and Housing Levy deductions. Uses the latest KRA FY 2024/25 tax bands with itemized breakdown.',
    category: 'finance-tax',
    keywords: ['PAYE calculator Kenya 2025', 'net salary Kenya', 'Kenya salary after tax', 'KRA tax calculator'],
    updateFrequency: 'annual',
    dataSource: 'Kenya Revenue Authority (KRA)',
    isLive: true,
    icon: '🧮',
  },
  {
    slug: 'mpesa-fee-calculator',
    title: 'M-Pesa Transaction Fee Calculator',
    shortTitle: 'M-Pesa Fees',
    description: 'Calculate exact M-Pesa fees for any transaction type. Includes smart "cheapest threshold" analysis showing when splitting transactions saves money.',
    category: 'finance-tax',
    keywords: ['mpesa charges calculator', 'mpesa tariff Kenya', 'how much does mpesa charge', 'safaricom charges'],
    updateFrequency: 'static',
    dataSource: 'Safaricom M-Pesa Tariff Schedule',
    isLive: true,
    icon: '📱',
  },
  {
    slug: 'cbc-curriculum',
    title: 'CBC Curriculum Explorer — Grades PP1 to 12',
    shortTitle: 'CBC Curriculum',
    description: 'Explore the complete Competency-Based Curriculum (CBC) structure. Find learning areas, strands, and sub-strands for every grade level from PP1 through Senior Secondary.',
    category: 'education-cbc',
    keywords: ['CBC curriculum Kenya', 'CBC learning areas', 'CBC subjects per grade', 'KICD curriculum'],
    updateFrequency: 'static',
    dataSource: 'Kenya Institute of Curriculum Development (KICD)',
    isLive: true,
    icon: '📚',
  },
  {
    slug: 'cbc-grade-age',
    title: 'CBC Grade & Age Checker',
    shortTitle: 'Grade-Age Checker',
    description: 'Enter your child\'s date of birth to find their correct CBC grade level, the 8-4-4 equivalent, expected learning areas, and upcoming milestones.',
    category: 'education-cbc',
    keywords: ['CBC grade age Kenya', 'what grade is my child CBC', 'PP1 PP2 age Kenya'],
    updateFrequency: 'static',
    dataSource: 'Ministry of Education / KICD',
    isLive: true,
    icon: '👶',
  },
  {
    slug: 'kuccps-cluster-calculator',
    title: 'KUCCPS Cluster Points Calculator 2025',
    shortTitle: 'KUCCPS Calculator',
    description: 'Enter your KCSE grades and instantly calculate cluster points for all university course clusters. Find which courses and universities you qualify for.',
    category: 'education-cbc',
    keywords: ['KUCCPS cluster calculator', 'cluster points Kenya', 'how to calculate cluster points KUCCPS', 'university admission Kenya'],
    updateFrequency: 'annual',
    dataSource: 'Kenya Universities and Colleges Central Placement Service (KUCCPS)',
    isLive: true,
    icon: '🎯',
  },
  {
    slug: 'kcse-grade-calculator',
    title: 'KCSE Mean Grade Calculator',
    shortTitle: 'KCSE Calculator',
    description: 'Calculate your KCSE mean grade from individual subject grades. See grade boundaries, career requirements, and university admission eligibility.',
    category: 'education-cbc',
    keywords: ['KCSE grade calculator', 'mean grade calculator Kenya', 'KNEC grading system'],
    updateFrequency: 'static',
    dataSource: 'Kenya National Examinations Council (KNEC)',
    isLive: true,
    icon: '📝',
  },
  {
    slug: 'public-holidays',
    title: 'Kenya Public Holidays 2025 & 2026',
    shortTitle: 'Public Holidays',
    description: 'Complete calendar of Kenya\'s gazetted public holidays with countdown timers, downloadable .ics calendar file, and historical context for each holiday.',
    category: 'government-legal',
    keywords: ['Kenya public holidays 2025', 'Kenya bank holidays', 'gazetted holidays Kenya 2026'],
    updateFrequency: 'annual',
    dataSource: 'Public Holidays Act (Cap 110)',
    isLive: true,
    icon: '📅',
  },
  {
    slug: 'number-plate-decoder',
    title: 'Kenya Number Plate Decoder',
    shortTitle: 'Plate Decoder',
    description: 'Decode any Kenya vehicle registration plate. Find the county of registration, approximate year, and plate type (private, government, diplomatic).',
    category: 'transport-travel',
    keywords: ['Kenya number plate meaning', 'KDA number plate county', 'Kenya car registration decoder'],
    updateFrequency: 'static',
    dataSource: 'National Transport and Safety Authority (NTSA)',
    isLive: true,
    icon: '🚗',
  },
  {
    slug: 'mobile-number-prefix',
    title: 'Kenya Mobile Number & Network Prefix Guide',
    shortTitle: 'Mobile Prefixes',
    description: 'Instantly identify which network a Kenya phone number belongs to. Complete prefix guide for Safaricom, Airtel, Telkom, and Fadhili with USSD codes.',
    category: 'data-reference',
    keywords: ['Kenya phone number prefix', 'which network is 0722', 'Safaricom Airtel Telkom prefixes'],
    updateFrequency: 'static',
    dataSource: 'Communications Authority of Kenya (CA)',
    isLive: true,
    icon: '📞',
  },
  {
    slug: 'school-terms',
    title: 'Kenya School Term Dates 2025 & 2026',
    shortTitle: 'School Terms',
    description: 'Official Ministry of Education school calendar with term dates, mid-term breaks, and exam periods for 2025 and 2026. Includes printable view.',
    category: 'education-cbc',
    keywords: ['Kenya school term dates 2025', 'MoE school calendar Kenya', 'school opening dates Kenya 2026'],
    updateFrequency: 'annual',
    dataSource: 'Ministry of Education',
    isLive: true,
    icon: '🏫',
  },
  {
    slug: 'stamp-duty-calculator',
    title: 'Kenya Stamp Duty & Property Transfer Cost Calculator',
    shortTitle: 'Stamp Duty Calculator',
    description: 'Calculate the total cost of transferring property in Kenya including stamp duty, LSK conveyancing fees, registration fees, and other charges.',
    category: 'finance-tax',
    keywords: ['stamp duty Kenya', 'property transfer cost Kenya', 'how much to transfer land Kenya', 'conveyancing fees Kenya'],
    updateFrequency: 'static',
    dataSource: 'Stamp Duty Act (Cap 480) & LSK Advocates Remuneration Order',
    isLive: true,
    icon: '🏠',
  },
  {
    slug: 'helb-calculator',
    title: 'HELB Loan Repayment Calculator Kenya',
    shortTitle: 'HELB Calculator',
    description: 'Calculate your HELB loan balance, monthly repayment obligation, total interest owed, and projected repayment completion year based on your loan details.',
    category: 'finance-tax',
    keywords: ['HELB loan repayment calculator', 'HELB interest calculator Kenya', 'how much HELB do I owe', 'HELB balance check'],
    updateFrequency: 'annual',
    dataSource: 'HELB Act & helb.co.ke',
    isLive: true,
    icon: '🎓',
  },
  {
    slug: 'housing-levy-calculator',
    title: 'Kenya Affordable Housing Levy (AHL) Calculator',
    shortTitle: 'Housing Levy',
    description: 'Calculate the Affordable Housing Levy deduction for both employee and employer, see the impact on your PAYE, and view annual projections.',
    category: 'finance-tax',
    keywords: ['affordable housing levy Kenya', '1.5% housing levy calculator', 'AHL Kenya', 'housing levy impact on salary'],
    updateFrequency: 'static',
    dataSource: 'Finance Act 2023, Section 84A',
    isLive: true,
    icon: '🏗️',
  },
  {
    slug: 'vehicle-insurance-calculator',
    title: 'Kenya Vehicle Insurance Minimum Premium Calculator',
    shortTitle: 'Vehicle Insurance',
    description: 'Calculate the minimum legal insurance premium for your vehicle in Kenya. Compare third party and comprehensive cover costs by vehicle class.',
    category: 'finance-tax',
    keywords: ['car insurance Kenya cost', 'minimum vehicle insurance Kenya', 'IRA motor insurance', 'third party insurance Kenya'],
    updateFrequency: 'annual',
    dataSource: 'Insurance Regulatory Authority (IRA)',
    isLive: true,
    icon: '🛡️',
  },
  {
    slug: 'kplc-token-calculator',
    title: 'KPLC Prepaid Electricity Token Calculator Kenya',
    shortTitle: 'Token Calculator',
    description: 'Enter the amount you want to pay for KPLC tokens and see exactly how many electricity units you will receive after fixed charges, VAT, and levies.',
    category: 'utilities-energy',
    keywords: ['KPLC units calculator Kenya', 'how many units will I get', 'electricity token calculator Kenya', 'KPLC prepaid calculator'],
    updateFrequency: 'annual',
    dataSource: 'EPRA / Kenya Power Tariff Schedule',
    isLive: true,
    icon: '⚡',
  },
  {
    slug: 'traffic-fines',
    title: 'Kenya NTSA Traffic Fines & Demerit Points Reference',
    shortTitle: 'Traffic Fines',
    description: 'Searchable reference of all Kenya traffic offences, fines, and NTSA demerit points. Filter by category — speed, DUI, documentation, parking, and more.',
    category: 'government-legal',
    keywords: ['NTSA fines Kenya 2025', 'traffic offence fines Kenya', 'speeding fine Kenya', 'demerit points Kenya'],
    updateFrequency: 'static',
    dataSource: 'Traffic Act (Cap 403) & NTSA',
    isLive: true,
    icon: '🚦',
  },
  {
    slug: 'passport-id-fees',
    title: 'Kenya Passport & National ID Fees Guide',
    shortTitle: 'Passport & ID Fees',
    description: 'Complete guide to Kenya passport types and fees, national ID costs, required documents, processing times, and step-by-step application process.',
    category: 'government-legal',
    keywords: ['Kenya passport fee 2025', 'national ID replacement cost Kenya', 'passport application Kenya', 'eCitizen passport'],
    updateFrequency: 'static',
    dataSource: 'Department of Immigration & National Registration Bureau',
    isLive: true,
    icon: '🛂',
  },
  {
    slug: 'driving-license-guide',
    title: 'Kenya Driving License Classes & Application Guide',
    shortTitle: 'Driving License',
    description: 'Complete guide to getting a driving license in Kenya — all license classes (A through G), step-by-step process, fees, required documents, and renewal info.',
    category: 'transport-travel',
    keywords: ['driving license classes Kenya', 'how to get driving license Kenya', 'NTSA driving test', 'driving license fee Kenya'],
    updateFrequency: 'static',
    dataSource: 'NTSA (ntsa.go.ke) & Traffic Act',
    isLive: true,
    icon: '🪪',
  },
  {
    slug: 'child-growth-schedule',
    title: 'Kenya Child Vaccination Schedule & Growth Tracker',
    shortTitle: 'Vaccination Schedule',
    description: 'Enter your child\'s date of birth to see their complete KEPI vaccination schedule, upcoming vaccines, expected weight range, and developmental milestones.',
    category: 'health-wellness',
    keywords: ['Kenya vaccination schedule baby', 'KEPI immunisation Kenya', 'child growth chart Kenya', 'baby vaccine schedule Kenya'],
    updateFrequency: 'static',
    dataSource: 'MOH Kenya KEPI & WHO Growth Standards',
    isLive: true,
    icon: '👶',
  },
  {
    slug: 'kenya-postal-codes',
    title: 'Kenya Postal Codes Directory',
    shortTitle: 'Postal Codes',
    description: 'Search Kenya postal codes by town name or code. Find the correct P.O. Box postal code for any town or city across all 47 counties.',
    category: 'data-reference',
    keywords: ['Kenya postal codes', 'Nairobi postal code', 'P.O. Box postal code Kenya', 'Kenya post office codes'],
    updateFrequency: 'static',
    dataSource: 'Posta Kenya (posta.co.ke)',
    isLive: true,
    icon: '📮',
  },
  // ── Phase 3 Tools ──
  {
    slug: 'water-bill-calculator',
    title: 'Kenya Water Bill Estimator',
    shortTitle: 'Water Bill Calculator',
    description: 'Estimate your monthly water bill for Nairobi (NCWSC), Mombasa, Kisumu, Nakuru, or Eldoret. See step-function tariff breakdown with sewerage charges.',
    category: 'utilities-energy',
    keywords: ['Nairobi water bill calculator', 'NCWSC tariff', 'how much water bill Kenya', 'water charges Kenya'],
    updateFrequency: 'periodic',
    dataSource: 'WASREB / Individual Water Utilities',
    isLive: true,
    icon: '💧',
  },
  {
    slug: 'solar-roi-calculator',
    title: 'Kenya Solar Energy ROI Calculator',
    shortTitle: 'Solar ROI Calculator',
    description: 'Calculate the return on investment for solar panels in Kenya. Enter your monthly electricity bill and location to see payback period, savings, and recommended system size.',
    category: 'utilities-energy',
    keywords: ['solar panel cost Kenya', 'solar ROI calculator Kenya', 'should I install solar Kenya', 'solar payback period Kenya'],
    updateFrequency: 'static',
    dataSource: 'KPLC Tariff / Kenya Meteorological Department',
    isLive: true,
    icon: '☀️',
  },
  {
    slug: 'ward-constituency-finder',
    title: 'Kenya Ward & Constituency Finder',
    shortTitle: 'Ward Finder',
    description: 'Find your constituency, ward, MP, Senator, Governor, and Women Representative. Select your county to see all elected officials and administrative boundaries.',
    category: 'government-legal',
    keywords: ['find my ward Kenya', 'my constituency Kenya', 'who is my MP Kenya', 'Kenya elected officials'],
    updateFrequency: 'static',
    dataSource: 'IEBC (2022 Election Data)',
    isLive: true,
    icon: '🗳️',
  },
  {
    slug: 'county-budget-tracker',
    title: 'Kenya County Budget Tracker',
    shortTitle: 'County Budgets',
    description: 'Track how all 47 county governments spend public money. Compare allocation, own-source revenue, expenditure, and budget absorption rates.',
    category: 'government-legal',
    keywords: ['county government budget Kenya', 'Nairobi county budget', 'Controller of Budget report Kenya', 'county expenditure Kenya'],
    updateFrequency: 'annual',
    dataSource: 'Controller of Budget (cob.go.ke)',
    isLive: true,
    icon: '📊',
  },
  {
    slug: 'national-parks-directory',
    title: 'Kenya National Parks & Wildlife Directory',
    shortTitle: 'National Parks',
    description: 'Explore Kenya\'s national parks, reserves, and conservancies. Find entry fees for citizens, residents, and tourists, plus wildlife highlights and best visiting seasons.',
    category: 'transport-travel',
    keywords: ['Kenya national parks fees', 'KWS park fees 2025', 'Kenya safari parks', 'Maasai Mara entry fee'],
    updateFrequency: 'annual',
    dataSource: 'Kenya Wildlife Service (kws.go.ke)',
    isLive: true,
    icon: '🦁',
  },
  {
    slug: 'nhif-hospital-finder',
    title: 'NHIF Accredited Hospital Finder Kenya',
    shortTitle: 'NHIF Hospitals',
    description: 'Search NHIF-accredited hospitals and clinics across Kenya. Filter by county, hospital level (2–6), and facility type (public, private, faith-based).',
    category: 'health-wellness',
    keywords: ['NHIF accredited hospitals Kenya', 'NHIF hospital near me', 'NHIF clinic Nairobi', 'SHA hospitals Kenya'],
    updateFrequency: 'periodic',
    dataSource: 'NHIF Accredited Providers List (nhif.or.ke)',
    isLive: true,
    icon: '🏥',
  },
  {
    slug: 'trademark-cost-kenya',
    title: 'Kenya Trademark & IP Registration Cost Guide',
    shortTitle: 'Trademark Costs',
    description: 'Calculate the cost of registering a trademark, patent, copyright, or utility model in Kenya via KIPI. Step-by-step fee breakdown with processing times.',
    category: 'business-investment',
    keywords: ['trademark registration Kenya cost', 'KIPI Kenya trademark fees', 'protect business name Kenya', 'patent registration Kenya'],
    updateFrequency: 'static',
    dataSource: 'Kenya Industrial Property Institute (kipi.go.ke)',
    isLive: true,
    icon: '™️',
  },
  {
    slug: 'real-estate-agent-checker',
    title: 'Kenya Real Estate Agent Verification Guide',
    shortTitle: 'Agent Checker',
    description: 'Learn how to verify if a real estate agent is registered with EARB. Protect yourself from property fraud with our verification guide and red flags checklist.',
    category: 'business-investment',
    keywords: ['verify real estate agent Kenya', 'registered estate agent Kenya', 'EARB Kenya', 'property fraud Kenya'],
    updateFrequency: 'annual',
    dataSource: 'Estate Agents Registration Board (earb.go.ke)',
    isLive: true,
    icon: '🏘️',
  },
  {
    slug: 'kenya-customs-restricted-items',
    title: 'Kenya Customs Restricted & Prohibited Items Guide',
    shortTitle: 'Customs Guide',
    description: 'Know what you can and cannot bring into Kenya. Complete guide to prohibited items, restricted goods requiring permits, and duty-free traveller allowances.',
    category: 'government-legal',
    keywords: ['what can I bring into Kenya', 'Kenya customs restrictions', 'prohibited items Kenya airport', 'Kenya duty free allowance'],
    updateFrequency: 'static',
    dataSource: 'KRA Customs & EAC Customs Management Act',
    isLive: true,
    icon: '🛃',
  },
  {
    slug: 'kenya-rainfall-patterns',
    title: 'Kenya Rainfall & Climate Reference by County',
    shortTitle: 'Rainfall Patterns',
    description: 'Explore rainfall patterns for all 47 Kenya counties. Monthly averages, rainy seasons, dry seasons, and climate zones — useful for farmers, tourists, and event planners.',
    category: 'data-reference',
    keywords: ['Kenya rainfall by county', 'when does it rain in Kenya', 'Kenya climate zones', 'Kenya rainy season'],
    updateFrequency: 'static',
    dataSource: 'Kenya Meteorological Department (meteo.go.ke)',
    isLive: true,
    icon: '🌧️',
  },
  {
    slug: 'kenyan-food-nutrition',
    title: 'Kenyan Food Nutrition Guide',
    shortTitle: 'Food Nutrition',
    description: 'Look up nutritional information for traditional Kenyan foods — ugali, sukuma wiki, nyama choma, githeri, and 60+ more. Calories, protein, carbs, and fat per serving.',
    category: 'data-reference',
    keywords: ['ugali calories', 'Kenya food nutrition facts', 'nyama choma nutritional value', 'Kenyan food calories'],
    updateFrequency: 'static',
    dataSource: 'FAO/WHO Food Composition Tables & KEMRI',
    isLive: true,
    icon: '🍲',
  },
];

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter(t => t.category === category);
}

export function getRelatedTools(slug: string, count: number = 4): Tool[] {
  const current = TOOLS.find(t => t.slug === slug);
  if (!current) return [];
  const sameCategory = TOOLS.filter(t => t.slug !== slug && t.category === current.category);
  const others = TOOLS.filter(t => t.slug !== slug && t.category !== current.category);
  return [...sameCategory, ...others].slice(0, count);
}

export function getCategoryInfo(category: ToolCategory) {
  return TOOL_CATEGORIES.find(c => c.id === category);
}
